### PR TITLE
Update Systers fork with commits from mailmain project.

### LINKED ISSUE #23: Update Postorius to reflect changes from main developement repo
## Description
Postorius has changed a lot since it was last cloned in 2015, updates need to be made to reflect updates at [https://gitlab.com/mailman/postorius](https://gitlab.com/mailman/postorius)

## Acceptance Criteria

- [x] Make require update

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

### PR DESCRIPTION
**Pull request by Monal5031**
### Description
This PR updates the Systers fork of postorius from the mailman project with the 300+ commits which were made during past 2-3 years.

Fixes #23 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Monal5031** [comment]
ping @naman1901 @pavankm please review.

**Comment by naman1901** [comment]
Wouldn't a better approach be to do it this way? https://help.github.com/articles/syncing-a-fork/

There's nothing to review here per se, so I'm just approving it for now, but consider the linked method.

**Comment by naman1901** [comment]
@prachi1210 best practice to sync the fork?

**Comment by pavankm** [comment]
Approved!

**Pull request merged**
